name: CI/CD Pipeline

on:
  push:
    branches: [main, feature/**]
  pull_request:
    branches: [main, feature/**]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/mcp-server
  IMAGE_TAG: v1.0.1

jobs:
  lint-and-audit:
    name: Lint & Dependency Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: flake8 .

      - name: Python Dependency Security Audit
        run: pip-audit

  docker-build-push:
    name: Build & Push Docker Image to GHCR
    runs-on: ubuntu-latest
    needs: lint-and-audit

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ env.IMAGE_TAG }} .

      - name: Push Docker images
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}

  trivy-scan:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Pull image from GHCR
        run: docker pull $IMAGE_NAME:${{ env.IMAGE_TAG }}

      - name: Scan the Docker image
        run: trivy image $IMAGE_NAME:${{ env.IMAGE_TAG }}
